updated comment in the github actions yml file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,58 +2,57 @@
 
 name: Build test and push note-service to docker
 on:
-  push:
-    branches: [master, main]
-    paths:
-      - 'note-service/**'
+    push:
+        branches: [master, main]
+        paths:
+            - "note-service/**" # since unit testing is only implemented for note-service
 
 jobs:
-  build-test-and-push-note-service:
-    runs-on: ubuntu-latest
+    build-test-and-push-note-service:
+        runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v3
+        steps:
+            - uses: actions/checkout@v3
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: 17
+            - name: Set up JDK 17
+              uses: actions/setup-java@v3
+              with:
+                  distribution: "temurin"
+                  java-version: 17
 
-      - name: Build with Gradle
-        working-directory: note-service
-        run: ./gradlew build -x test
+            - name: Build with Gradle
+              working-directory: note-service
+              run: ./gradlew build -x test
 
-      - name: Run tests with Gradle
-        working-directory: note-service
-        env:
-          SCRIBBLE_NOTE_SERVICE_PORT: ${{ secrets.SCRIBBLE_NOTE_SERVICE_PORT }}
-          SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${{ secrets.SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI }}
-          SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID }}
-          SCRIBBLE_AUTH_AWS_COGNITO_JWK: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_JWK }}
-          SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID }}
-          SCRIBBLE_AUTH_AWS_COGNITO_REGION: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_REGION }}
-          SCRIBBLE_AUTH_AWS_ACCESS_KEY: ${{ secrets.SCRIBBLE_AUTH_AWS_ACCESS_KEY }}
-          SCRIBBLE_AUTH_AWS_SECRET_KEY: ${{ secrets.SCRIBBLE_AUTH_AWS_SECRET_KEY }}
-          SCRIBBLE_AUTH_AWS_DEFAULT_REGION: ${{ secrets.SCRIBBLE_AUTH_AWS_DEFAULT_REGION }}
-        run: |
-          ./gradlew test
-          # Check the exit code of the previous command
-          if [ "$?" -ne 0 ]; then
-            exit 1
-          fi
+            - name: Run tests with Gradle
+              working-directory: note-service
+              env:
+                  SCRIBBLE_NOTE_SERVICE_PORT: ${{ secrets.SCRIBBLE_NOTE_SERVICE_PORT }}
+                  SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${{ secrets.SCRIBBLE_AUTH_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI }}
+                  SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_USERPOOL_ID }}
+                  SCRIBBLE_AUTH_AWS_COGNITO_JWK: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_JWK }}
+                  SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_CLIENT_ID }}
+                  SCRIBBLE_AUTH_AWS_COGNITO_REGION: ${{ secrets.SCRIBBLE_AUTH_AWS_COGNITO_REGION }}
+                  SCRIBBLE_AUTH_AWS_ACCESS_KEY: ${{ secrets.SCRIBBLE_AUTH_AWS_ACCESS_KEY }}
+                  SCRIBBLE_AUTH_AWS_SECRET_KEY: ${{ secrets.SCRIBBLE_AUTH_AWS_SECRET_KEY }}
+                  SCRIBBLE_AUTH_AWS_DEFAULT_REGION: ${{ secrets.SCRIBBLE_AUTH_AWS_DEFAULT_REGION }}
+              run: |
+                  ./gradlew test
+                  # Check the exit code of the previous command
+                  if [ "$?" -ne 0 ]; then
+                    exit 1
+                  fi
 
-      - name: Build and push Docker image
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-          IMAGE_NAME: lakshyajit165/scribble-note-service
-          TAG: latest
-        run: |
-          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-          docker build -t $IMAGE_NAME:$TAG ./note-service
-          docker push $IMAGE_NAME:$TAG
-
+            - name: Build and push Docker image
+              env:
+                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+                  IMAGE_NAME: lakshyajit165/scribble-note-service
+                  TAG: latest
+              run: |
+                  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+                  docker build -t $IMAGE_NAME:$TAG ./note-service
+                  docker push $IMAGE_NAME:$TAG
 
 # Workflow to trigger jenkins build
 
@@ -89,6 +88,3 @@ jobs:
 #           }" > payload.json
 #           curl -X POST -H "Content-Type: application/json" -H "ngrok-skip-browser-warning: true" -d @payload.json https://1801-103-186-41-136.ngrok-free.app/generic-webhook-trigger/invoke?token=scribble_build_job
 
-
-
-  
